"""add_invoice_snapshot_fields

Revision ID: fe1e46782560
Revises: 84f3e71da89b
Create Date: 2026-06-26 09:44:53.189061
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1e46782560'
down_revision: Union[str, None] = '84f3e71da89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.add_column('invoices', sa.Column('client_cedula_snapshot', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('client_phone_snapshot', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('client_address_snapshot', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('clave_acceso_snapshot', sa.String(length=49), nullable=True))
    op.add_column('invoices', sa.Column('sri_xml_snapshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'sri_xml_snapshot')
    op.drop_column('invoices', 'clave_acceso_snapshot')
    op.drop_column('invoices', 'client_address_snapshot')
    op.drop_column('invoices', 'client_phone_snapshot')
    op.drop_column('invoices', 'client_cedula_snapshot')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # ### end Alembic commands ###