"""Users & roles use cases."""

from app.application.users.dto import (
    AssignRolesDto,
    CreateUserDto,
    ErrorLogResponseDto,
    RoleResponseDto,
    UpdateUserDto,
    UserResponseDto,
)
from app.application.users.handlers import (
    AssignRolesCommand,
    AssignRolesHandler,
    CreateUserCommand,
    CreateUserHandler,
    DeleteUserCommand,
    DeleteUserHandler,
    GetErrorLogsHandler,
    GetErrorLogsQuery,
    GetRolesHandler,
    GetRolesQuery,
    GetUserHandler,
    GetUserQuery,
    GetUserRolesHandler,
    GetUserRolesQuery,
    GetUsersHandler,
    GetUsersQuery,
    UpdateUserCommand,
    UpdateUserHandler,
)

__all__ = [
    "AssignRolesCommand",
    "AssignRolesDto",
    "AssignRolesHandler",
    "CreateUserCommand",
    "CreateUserDto",
    "CreateUserHandler",
    "DeleteUserCommand",
    "DeleteUserHandler",
    "ErrorLogResponseDto",
    "GetErrorLogsHandler",
    "GetErrorLogsQuery",
    "GetRolesHandler",
    "GetRolesQuery",
    "GetUserHandler",
    "GetUserQuery",
    "GetUserRolesHandler",
    "GetUserRolesQuery",
    "GetUsersHandler",
    "GetUsersQuery",
    "RoleResponseDto",
    "UpdateUserCommand",
    "UpdateUserDto",
    "UpdateUserHandler",
    "UserResponseDto",
]
