"""Unit tests for the Ecuadorian cédula validator (módulo 10).

Valid cédulas below were generated by hand: pick 9 digits, compute
verifier via (10 - (sum % 10)) % 10, append it. Example for body
'171234567' (sum = 35) → verifier = 5 → full cédula '1712345675'.
"""

from __future__ import annotations

import pytest

from app.core.exceptions import BusinessError
from app.domain.value_objects.cedula import Cedula


@pytest.mark.parametrize(
    "valid_cedula",
    [
        "1712345675",  # Pichincha (17), sum 35 → verif 5
        "0912345675",  # Guayas (09), sum 35 → verif 5
        "0100000009",  # Azuay (01), sum 1 → verif 9
        "1799999998",  # Pichincha (17), sum 72 → verif 8
    ],
)
def test_valid_cedulas_pass(valid_cedula: str) -> None:
    c = Cedula(valid_cedula)
    assert c.value == valid_cedula


@pytest.mark.parametrize(
    "invalid_cedula",
    [
        "1712345670",  # wrong verifier (computed: 5)
        "1712345678",  # wrong verifier (computed: 5)
        "0012345678",  # invalid province 00
        "2512345678",  # invalid province 25 (max 24)
        "0000000000",  # all zeros rejected
        "171234567",   # too short (9 digits)
        "17123456789",  # too long (11 digits)
        "171234567A",  # non-numeric
        "",            # empty string
        "1111111111",  # all same digit
        "3000000001",  # province 30 is NOT accepted (we are strict)
    ],
)
def test_invalid_cedulas_raise(invalid_cedula: str) -> None:
    with pytest.raises(BusinessError, match="Cédula inválida"):
        Cedula(invalid_cedula)


def test_str_returns_value() -> None:
    assert str(Cedula("1712345675")) == "1712345675"